### ISSUE TITLE
getting weird error on my terminal

### ISSUE THREAD

**Issue by vr1eva** [chalk/supports-color#158] opened 2024-12-28 22:42 UTC
Im running Node LTS v23.3.5 and I got this error this morning:
![image](https://github.com/user-attachments/assets/c26df84b-9ddf-45b8-8ecc-592ccfb8dbc9)

**Comment by Qix-** [comment] 2024-12-30 00:32
Dupe of debug-js/debug#975

**Closed by Qix-** 2024-12-30 00:32 UTC
