### ISSUE TITLE
Implementing the NO_COLOR environment variable standard

### ISSUE THREAD

**Issue by stevenmhunt** [chalk/supports-color#104] opened 2019-10-09 18:49 UTC
There is a [proposed standard regarding disabling color output](https://no-color.org/) which this project should consider supporting. It behaves very similarly to `FORCE_COLOR=0` except that it is a standard being recognized by an increasing number of languages and libraries.

**Comment by Qix-** [comment] 2019-10-09 19:40
Duplicate of #74.

**Closed by Qix-** 2019-10-09 19:40 UTC
