### ISSUE TITLE
NPM scripts in Git Bash for Windows / MinGW64 are identified incorrectly

### ISSUE THREAD

**Issue by MarkTiedemann** [chalk/supports-color#38] opened 2016-05-19 10:39 UTC
When running NPM scripts in Git Bash for Windows / MinGW64, `chalk/supports-color` returns `false`, even though `chalk/ansi-styles` can output colors. (See: [https://github.com/MarkTiedemann/supports-color-bug](https://github.com/MarkTiedemann/supports-color-bug))

If `node` is run directly, without NPM scripts, `supports-color` correctly returns `true`.

If used with `cmder` instead of Git Bash for Windows / MinGW64, both with and without NPM scripts, it correctly returns `true`.

Running latest Node, NPM, and Git for Windows version.

EDIT: Not sure how this is related to [https://github.com/chalk/supports-color/issues/36](https://github.com/chalk/supports-color/issues/36). Is this a `wontfix` as well?

**Comment by sindresorhus** [comment] 2016-05-19 11:06
Yes, duplicate of https://github.com/chalk/supports-color/issues/36. Not an issue we can work around unfortunately.

-

I would storngly recommend just installing the real Bash: https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/

**Closed by sindresorhus** 2016-05-19 11:06 UTC
