### ISSUE TITLE
Fails on Cygwin with $TERM=xterm 

### ISSUE THREAD

**Issue by emigenix** [chalk/supports-color#45] opened 2016-08-24 16:47 UTC
Tried the test under Cygwin where I have at least 16 color palette, but this script fails, telling me otherwise.
```
$ supports-color --256
$ echo $?
1
```

**Comment by sindresorhus** [comment] 2016-08-24 19:33
Duplicate of https://github.com/chalk/supports-color/issues/38.

**Closed by sindresorhus** 2016-08-24 19:33 UTC
